server:
  port: 4000

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: SCIENTIST-SERVICE
          uri: lb://SCIENTIST-SERVICE
          predicates:
            - Path=/v1/api/scientist/**
        - id: ARTICLE-SERVICE
          uri: lb://ARTICLE-SERVICE
          predicates:
            - Path=/v1/api/article/**
          filters:
            - AuthFilter

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.49.2:31002/eureka/
#      defaultZone: http://172.17.0.2:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: 192.168.49.2
#    hostname: 172.17.0.3
#    hostname: 192.168.1.20
    prefer-ip-address: true
#    hostname: localhost