server:
  port: 4000

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: CLIENT-SERVICE
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/client/**
        - id: ARTICLE-SERVICE
          uri: lb://ARTICLE-SERVICE
          predicates:
            - Path=/article/**
          filters:
            - AuthFilter

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost